import Head from "next/head";
import About from "../components/About/About";
import Hero from "../components/Hero/Hero";
import Navigation from "../components/Navigation/Navigation";
import Playground from "../components/Playground/Playground";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ante Petkovic | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Hero />
      <About />
      <Playground />
    </div>
  );
}
